/**
 * @file c_printer.c
 * @author Nathan Bourgeois (iridescentrosesfall@gmail.com)
 * @brief Prints a program into C
 * @version 1.0
 * @date 2021-11-17
 * 
 * @copyright Copyright (c) 2021
 * 
 */
 #include "c_printer.h"
 
void emit_header(FILE* fp, const char* filename){
    fprintf(fp, "/* File generated by HolyC Translator! File: %s */\n", filename);
}

void emit_preprocessor(FILE* fp, PreProcessor* statement) {
    fprintf(fp, "%s\n", statement->text.ptr);
}

const char* type_to_string(Type type){
    switch(type){
        case TYPE_U0: {
            return "void";
        }
        case TYPE_U8: {
            return "unsigned char";
        }
        case TYPE_U16: {
            return "unsigned short int";
        }
        case TYPE_U32: {
            return "unsigned long int";
        }
        case TYPE_U64: {
            return "unsigned long long int";
        }
        
        case TYPE_I8: {
            return "signed char";
        }
        case TYPE_I16: {
            return "signed short int";
        }
        case TYPE_I32: {
            return "signed long int";
        }
        case TYPE_I64: {
            return "signed long long int";
        }

        case TYPE_F64: {
            return "double";
        }
    }

    return "(null)";
}

void emit_declaration(FILE* fp, Declaration* statement) {
    if(statement->is_function){

    }else{
        fprintf(fp, "%s%s %s;", type_to_string(statement->type), statement->pointer ? "*" : "", statement->identifier.ptr);
    }
}

void emit_statement_block(FILE* fp, struct ScopeBlock* block){
    for(size_t i = 0; i < block->statement_list->size; i++){
        Statement* statement = list_at(block->statement_list, i);

        switch (statement->type) {
            case STATEMENT_TYPE_DECLARATION: {
                emit_declaration(fp, (Declaration*)statement->statementData);
                break;
            }
            
            case STATEMENT_TYPE_DEFINITION: {
                break;
            }
            
            case STATEMENT_TYPE_EXPRESSION: {
                break;
            }

            case STATEMENT_TYPE_PREPROCESSOR: {
                emit_preprocessor(fp, (PreProcessor*)statement->statementData);
                break;
            }
        
            default: {
                CHECK_FAILED("INVALID STATEMENT TYPE: %d", statement->type);
                break;
            }
        }
    }
}


void emit_c(Program* program, const char* filename){
    FILE* fp = fopen(filename, "w");
    CHECK_NOT_NULL(fp, "Could not access output file!");

    emit_header(fp, filename);
    emit_statement_block(fp, &program->block);

    fclose(fp);
}