name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: tests
        path: out/
        if-no-files-found: error
        retention-days: 30
